
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique


  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: Milestone1_1
    description: "To calculate Monthly average NAV, Repurchase & Sale Price for each scheme"

  - name: Milsetone1_2
    description: "To find out each scheme’s Max and Min NAV value and Date it occurred"
